import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import SearchBar from "./components/SearchBar";
import { Provider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="bg-white">
            <Header />
            <div>
              <SearchBar />
            </div>
            {children}
          </div>
      </body>
    </html>
  );
}
